language: rust
sudo: false

matrix:
  include:
    - rust: 1.21.0
    - rust: stable
    - os: osx
      before_install:
        - export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include
        - export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib
    - rust: beta
    - rust: nightly

    - rust: nightly
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      script:
        - cargo doc --no-deps
        - cargo doc --no-deps --manifest-path libssh2-sys/Cargo.toml
      after_success:
        - travis-cargo --only nightly doc-upload

before_script:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - telnet localhost 22 &

script:
  - cargo build
  - cargo test
  - rustdoc --test README.md -L target
  - cargo run --manifest-path systest/Cargo.toml

env:
  global:
    secure: "Pv35wAFBLDqTGXot1aq7JtDAzwWXxTQahl3MeH9T1fdq2SqNdvXQazRJqDZcpeTO5EH+g2hLShiz9bije2746hzoIyb4GFt1II35a2hff2hBaxsaBb2BCPc7wEjW6u8QQ+PZXpauO2OQrlPwJUBpIActGp6NOI/Et4a3eFBOpx4="

notifications:
  email:
    on_success: never

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
