[package]
name = "ssh2"
version = "0.3.3"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
keywords = ["ssh"]
readme = "README.md"
repository = "https://github.com/alexcrichton/ssh2-rs"
homepage = "https://github.com/alexcrichton/ssh2-rs"
documentation = "https://docs.rs/ssh2-rs"
description = """
Bindings to libssh2 for interacting with SSH servers and executing remote
commands, forwarding local ports, etc.
"""

[dependencies]
bitflags = "1.0.4"
libc = "0.2"
libssh2-sys = { path = "libssh2-sys", version = "0.2.4" }

[dev-dependencies]
tempdir = "0.3"

[workspace]
members = ['systest']
